# Generated by Django 5.2.6 on 2025-11-24 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='sexo',
            field=models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra')], default='macho', max_length=10),
        ),
        migrations.AddField(
            model_name='mascota',
            name='ubicacion',
            field=models.CharField(blank=True, default='Sin especificar', max_length=100),
        ),
    ]
